// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


import './mobile.css'
import './desktop.css'
const Home = () =>{
  return(
<html>
  <body>
    <header>
    <div className="homepageHeader">
        <img src="" width="112px" height="100px" alt="cantor college logo" className="cantorLogo"/>
        <h1 className="cantorTitle">Cantor Home</h1>
      </div>
      <div className="navigationBar">
            <div className="courses sectionBar">
                Courses
            </div>
            <div className="facilities sectionBar">
                Facilities
            </div>
            <div className="campusMap sectionBar">
                Campus Map and Where to Find Us
            </div>
            <div className="learningResources sectionBar">
                Learning Resources
            </div>
            <div className="importantInformation sectionBar">
                Important Information
            </div>
            <div className="workingWithBusinesses sectionBar">
                Working with Businesses
            </div>
      </div>
    </header>
    <main>

<div className="infoBox" id="welcomeBox">
<h2 id="aboutUsTitle"><b>About Us</b></h2>
  
  <img src="" alt="image of cantor college" width="1000" height="750" 
className="welcomeImage" id="cantorPics" />

<p id="welcomeText">
Cantor College was established in 1989 to specialize in Computing and Design.   
At Cantor College, we want to give students the education they need to achieve their career aims, 
leaving them equipped with the knowledge, skills and experience to succeed. 
Cantor College gives you the opportunities that can give you the edge when you enter the world of work, 
through our teaching and our links to some of the world's leading researchers and employers. 
Our students have gone on to successful careers in a wide range of industries across the globe.  
Whatever your ambitions, our learning and support can help to get the most out of your time with Cantor College, 
both as a student and in your future career.
</p>
</div>
</main>
<footer>

</footer>
</body>
</html>

)
}
export default Home;
